'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSDL_BODEGAS
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://sap.com/xi/AP/Common/Global")>  _
    Partial Public Class StandardFaultMessage
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private standardField As ExchangeFaultData
        
        Private additionField As StandardFaultMessageExtension
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property standard() As ExchangeFaultData
            Get
                Return Me.standardField
            End Get
            Set
                Me.standardField = value
                Me.RaisePropertyChanged("standard")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property addition() As StandardFaultMessageExtension
            Get
                Return Me.additionField
            End Get
            Set
                Me.additionField = value
                Me.RaisePropertyChanged("addition")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sap.com/xi/AP/Common/Global")>  _
    Partial Public Class ExchangeFaultData
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private faultTextField As String
        
        Private faultUrlField As String
        
        Private faultDetailField() As ExchangeLogData
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property faultText() As String
            Get
                Return Me.faultTextField
            End Get
            Set
                Me.faultTextField = value
                Me.RaisePropertyChanged("faultText")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property faultUrl() As String
            Get
                Return Me.faultUrlField
            End Get
            Set
                Me.faultUrlField = value
                Me.RaisePropertyChanged("faultUrl")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("faultDetail", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property faultDetail() As ExchangeLogData()
            Get
                Return Me.faultDetailField
            End Get
            Set
                Me.faultDetailField = value
                Me.RaisePropertyChanged("faultDetail")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sap.com/xi/AP/Common/Global")>  _
    Partial Public Class ExchangeLogData
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private severityField As String
        
        Private textField As String
        
        Private urlField As String
        
        Private idField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property severity() As String
            Get
                Return Me.severityField
            End Get
            Set
                Me.severityField = value
                Me.RaisePropertyChanged("severity")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property text() As String
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
                Me.RaisePropertyChanged("text")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property url() As String
            Get
                Return Me.urlField
            End Get
            Set
                Me.urlField = value
                Me.RaisePropertyChanged("url")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("id")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sap.com/xi/AP/Common/Global")>  _
    Partial Public Class StandardFaultMessageExtension
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private logField As Log
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property Log() As Log
            Get
                Return Me.logField
            End Get
            Set
                Me.logField = value
                Me.RaisePropertyChanged("Log")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sap.com/xi/AP/Common/GDT")>  _
    Partial Public Class Log
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private businessDocumentProcessingResultCodeField As String
        
        Private maximumLogItemSeverityCodeField As String
        
        Private itemField() As LogItem
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token", Order:=0)>  _
        Public Property BusinessDocumentProcessingResultCode() As String
            Get
                Return Me.businessDocumentProcessingResultCodeField
            End Get
            Set
                Me.businessDocumentProcessingResultCodeField = value
                Me.RaisePropertyChanged("BusinessDocumentProcessingResultCode")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token", Order:=1)>  _
        Public Property MaximumLogItemSeverityCode() As String
            Get
                Return Me.maximumLogItemSeverityCodeField
            End Get
            Set
                Me.maximumLogItemSeverityCodeField = value
                Me.RaisePropertyChanged("MaximumLogItemSeverityCode")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("Item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property Item() As LogItem()
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
                Me.RaisePropertyChanged("Item")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sap.com/xi/AP/Common/GDT")>  _
    Partial Public Class LogItem
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private typeIDField As String
        
        Private categoryCodeField As LogItemCategoryCode
        
        Private severityCodeField As String
        
        Private referenceObjectNodeSenderTechnicalIDField As String
        
        Private referenceMessageElementNameField As String
        
        Private noteField As String
        
        Private noteTemplateTextField As String
        
        Private logItemNotePlaceholderSubstitutionListField As LogItemNotePlaceholderSubstitutionList
        
        Private webURIField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token", Order:=0)>  _
        Public Property TypeID() As String
            Get
                Return Me.typeIDField
            End Get
            Set
                Me.typeIDField = value
                Me.RaisePropertyChanged("TypeID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property CategoryCode() As LogItemCategoryCode
            Get
                Return Me.categoryCodeField
            End Get
            Set
                Me.categoryCodeField = value
                Me.RaisePropertyChanged("CategoryCode")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token", Order:=2)>  _
        Public Property SeverityCode() As String
            Get
                Return Me.severityCodeField
            End Get
            Set
                Me.severityCodeField = value
                Me.RaisePropertyChanged("SeverityCode")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token", Order:=3)>  _
        Public Property ReferenceObjectNodeSenderTechnicalID() As String
            Get
                Return Me.referenceObjectNodeSenderTechnicalIDField
            End Get
            Set
                Me.referenceObjectNodeSenderTechnicalIDField = value
                Me.RaisePropertyChanged("ReferenceObjectNodeSenderTechnicalID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property ReferenceMessageElementName() As String
            Get
                Return Me.referenceMessageElementNameField
            End Get
            Set
                Me.referenceMessageElementNameField = value
                Me.RaisePropertyChanged("ReferenceMessageElementName")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property Note() As String
            Get
                Return Me.noteField
            End Get
            Set
                Me.noteField = value
                Me.RaisePropertyChanged("Note")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property NoteTemplateText() As String
            Get
                Return Me.noteTemplateTextField
            End Get
            Set
                Me.noteTemplateTextField = value
                Me.RaisePropertyChanged("NoteTemplateText")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property LogItemNotePlaceholderSubstitutionList() As LogItemNotePlaceholderSubstitutionList
            Get
                Return Me.logItemNotePlaceholderSubstitutionListField
            End Get
            Set
                Me.logItemNotePlaceholderSubstitutionListField = value
                Me.RaisePropertyChanged("LogItemNotePlaceholderSubstitutionList")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="anyURI", Order:=8)>  _
        Public Property WebURI() As String
            Get
                Return Me.webURIField
            End Get
            Set
                Me.webURIField = value
                Me.RaisePropertyChanged("WebURI")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sap.com/xi/AP/Common/GDT")>  _
    Partial Public Class LogItemCategoryCode
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private listIDField As String
        
        Private listVersionIDField As String
        
        Private listAgencyIDField As String
        
        Private listAgencySchemeIDField As String
        
        Private listAgencySchemeAgencyIDField As AgencyIdentificationCode
        
        Private listAgencySchemeAgencyIDFieldSpecified As Boolean
        
        Private valueField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property listID() As String
            Get
                Return Me.listIDField
            End Get
            Set
                Me.listIDField = value
                Me.RaisePropertyChanged("listID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property listVersionID() As String
            Get
                Return Me.listVersionIDField
            End Get
            Set
                Me.listVersionIDField = value
                Me.RaisePropertyChanged("listVersionID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property listAgencyID() As String
            Get
                Return Me.listAgencyIDField
            End Get
            Set
                Me.listAgencyIDField = value
                Me.RaisePropertyChanged("listAgencyID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property listAgencySchemeID() As String
            Get
                Return Me.listAgencySchemeIDField
            End Get
            Set
                Me.listAgencySchemeIDField = value
                Me.RaisePropertyChanged("listAgencySchemeID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property listAgencySchemeAgencyID() As AgencyIdentificationCode
            Get
                Return Me.listAgencySchemeAgencyIDField
            End Get
            Set
                Me.listAgencySchemeAgencyIDField = value
                Me.RaisePropertyChanged("listAgencySchemeAgencyID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property listAgencySchemeAgencyIDSpecified() As Boolean
            Get
                Return Me.listAgencySchemeAgencyIDFieldSpecified
            End Get
            Set
                Me.listAgencySchemeAgencyIDFieldSpecified = value
                Me.RaisePropertyChanged("listAgencySchemeAgencyIDSpecified")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="token")>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
                Me.RaisePropertyChanged("Value")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sap.com/xi/BASIS/Global")>  _
    Public Enum AgencyIdentificationCode
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("1")>  _
        Item1
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("5")>  _
        Item5
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("6")>  _
        Item6
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("16")>  _
        Item16
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("17")>  _
        Item17
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("84")>  _
        Item84
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("107")>  _
        Item107
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("109")>  _
        Item109
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("112")>  _
        Item112
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("113")>  _
        Item113
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("114")>  _
        Item114
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("116")>  _
        Item116
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("117")>  _
        Item117
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("124")>  _
        Item124
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("130")>  _
        Item130
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("131")>  _
        Item131
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("138")>  _
        Item138
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("142")>  _
        Item142
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("146")>  _
        Item146
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("262")>  _
        Item262
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("296")>  _
        Item296
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("310")>  _
        Item310
    End Enum
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sap.com/xi/AP/Common/GDT")>  _
    Partial Public Class LogItemNotePlaceholderSubstitutionList
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private firstPlaceholderIDField As String
        
        Private secondPlaceholderIDField As String
        
        Private thirdPlaceholderIDField As String
        
        Private fourthPlaceholderIDField As String
        
        Private firstPlaceholderSubstitutionTextField As String
        
        Private secondPlaceholderSubstitutionTextField As String
        
        Private thirdPlaceholderSubstitutionTextField As String
        
        Private fourthPlaceholderSubstitutionTextField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token", Order:=0)>  _
        Public Property FirstPlaceholderID() As String
            Get
                Return Me.firstPlaceholderIDField
            End Get
            Set
                Me.firstPlaceholderIDField = value
                Me.RaisePropertyChanged("FirstPlaceholderID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token", Order:=1)>  _
        Public Property SecondPlaceholderID() As String
            Get
                Return Me.secondPlaceholderIDField
            End Get
            Set
                Me.secondPlaceholderIDField = value
                Me.RaisePropertyChanged("SecondPlaceholderID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token", Order:=2)>  _
        Public Property ThirdPlaceholderID() As String
            Get
                Return Me.thirdPlaceholderIDField
            End Get
            Set
                Me.thirdPlaceholderIDField = value
                Me.RaisePropertyChanged("ThirdPlaceholderID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token", Order:=3)>  _
        Public Property FourthPlaceholderID() As String
            Get
                Return Me.fourthPlaceholderIDField
            End Get
            Set
                Me.fourthPlaceholderIDField = value
                Me.RaisePropertyChanged("FourthPlaceholderID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property FirstPlaceholderSubstitutionText() As String
            Get
                Return Me.firstPlaceholderSubstitutionTextField
            End Get
            Set
                Me.firstPlaceholderSubstitutionTextField = value
                Me.RaisePropertyChanged("FirstPlaceholderSubstitutionText")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property SecondPlaceholderSubstitutionText() As String
            Get
                Return Me.secondPlaceholderSubstitutionTextField
            End Get
            Set
                Me.secondPlaceholderSubstitutionTextField = value
                Me.RaisePropertyChanged("SecondPlaceholderSubstitutionText")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property ThirdPlaceholderSubstitutionText() As String
            Get
                Return Me.thirdPlaceholderSubstitutionTextField
            End Get
            Set
                Me.thirdPlaceholderSubstitutionTextField = value
                Me.RaisePropertyChanged("ThirdPlaceholderSubstitutionText")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property FourthPlaceholderSubstitutionText() As String
            Get
                Return Me.fourthPlaceholderSubstitutionTextField
            End Get
            Set
                Me.fourthPlaceholderSubstitutionTextField = value
                Me.RaisePropertyChanged("FourthPlaceholderSubstitutionText")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://0014438665-one-off.sap.com/Y640YVQUY_")>  _
    Partial Public Class EX_BodegaExistencia_BodegaCreateConfirmation
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private sAP_UUIDField As String
        
        Private entryField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token", Order:=0)>  _
        Public Property SAP_UUID() As String
            Get
                Return Me.sAP_UUIDField
            End Get
            Set
                Me.sAP_UUIDField = value
                Me.RaisePropertyChanged("SAP_UUID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token", Order:=1)>  _
        Public Property Entry() As String
            Get
                Return Me.entryField
            End Get
            Set
                Me.entryField = value
                Me.RaisePropertyChanged("Entry")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://0014438665-one-off.sap.com/Y640YVQUY_")>  _
    Partial Public Class EX_BodegaExistencia_BodegaCreateConfirmationMessage_sync
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private eX_BodegaField As EX_BodegaExistencia_BodegaCreateConfirmation
        
        Private logField As Log
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property EX_Bodega() As EX_BodegaExistencia_BodegaCreateConfirmation
            Get
                Return Me.eX_BodegaField
            End Get
            Set
                Me.eX_BodegaField = value
                Me.RaisePropertyChanged("EX_Bodega")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property Log() As Log
            Get
                Return Me.logField
            End Get
            Set
                Me.logField = value
                Me.RaisePropertyChanged("Log")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sap.com/xi/AP/Common/GDT")>  _
    Partial Public Class Quantity
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private unitCodeField As String
        
        Private valueField As Decimal
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property unitCode() As String
            Get
                Return Me.unitCodeField
            End Get
            Set
                Me.unitCodeField = value
                Me.RaisePropertyChanged("unitCode")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As Decimal
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
                Me.RaisePropertyChanged("Value")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sap.com/xi/AP/Common/GDT")>  _
    Partial Public Class Text
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private languageCodeField As String
        
        Private valueField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="language")>  _
        Public Property languageCode() As String
            Get
                Return Me.languageCodeField
            End Get
            Set
                Me.languageCodeField = value
                Me.RaisePropertyChanged("languageCode")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
                Me.RaisePropertyChanged("Value")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://0014438665-one-off.sap.com/Y640YVQUY_")>  _
    Partial Public Class EX_BodegaExistencia_BodegaCreateRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private entryField As String
        
        Private codAlmacenField As Text
        
        Private nalmacenField As Text
        
        Private citemField As Text
        
        Private ditemField As Text
        
        Private cantDispField As Quantity
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token", Order:=0)>  _
        Public Property Entry() As String
            Get
                Return Me.entryField
            End Get
            Set
                Me.entryField = value
                Me.RaisePropertyChanged("Entry")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property CodAlmacen() As Text
            Get
                Return Me.codAlmacenField
            End Get
            Set
                Me.codAlmacenField = value
                Me.RaisePropertyChanged("CodAlmacen")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property Nalmacen() As Text
            Get
                Return Me.nalmacenField
            End Get
            Set
                Me.nalmacenField = value
                Me.RaisePropertyChanged("Nalmacen")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property Citem() As Text
            Get
                Return Me.citemField
            End Get
            Set
                Me.citemField = value
                Me.RaisePropertyChanged("Citem")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property Ditem() As Text
            Get
                Return Me.ditemField
            End Get
            Set
                Me.ditemField = value
                Me.RaisePropertyChanged("Ditem")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property CantDisp() As Quantity
            Get
                Return Me.cantDispField
            End Get
            Set
                Me.cantDispField = value
                Me.RaisePropertyChanged("CantDisp")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sap.com/xi/AP/Common/GDT")>  _
    Partial Public Class UUID
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private schemeIDField As String
        
        Private schemeAgencyIDField As String
        
        Private valueField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property schemeID() As String
            Get
                Return Me.schemeIDField
            End Get
            Set
                Me.schemeIDField = value
                Me.RaisePropertyChanged("schemeID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property schemeAgencyID() As String
            Get
                Return Me.schemeAgencyIDField
            End Get
            Set
                Me.schemeAgencyIDField = value
                Me.RaisePropertyChanged("schemeAgencyID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="token")>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
                Me.RaisePropertyChanged("Value")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sap.com/xi/AP/Common/GDT")>  _
    Partial Public Class BusinessDocumentMessageID
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private schemeIDField As String
        
        Private schemeAgencyIDField As String
        
        Private schemeAgencySchemeAgencyIDField As AgencyIdentificationCode
        
        Private schemeAgencySchemeAgencyIDFieldSpecified As Boolean
        
        Private valueField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property schemeID() As String
            Get
                Return Me.schemeIDField
            End Get
            Set
                Me.schemeIDField = value
                Me.RaisePropertyChanged("schemeID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property schemeAgencyID() As String
            Get
                Return Me.schemeAgencyIDField
            End Get
            Set
                Me.schemeAgencyIDField = value
                Me.RaisePropertyChanged("schemeAgencyID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property schemeAgencySchemeAgencyID() As AgencyIdentificationCode
            Get
                Return Me.schemeAgencySchemeAgencyIDField
            End Get
            Set
                Me.schemeAgencySchemeAgencyIDField = value
                Me.RaisePropertyChanged("schemeAgencySchemeAgencyID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property schemeAgencySchemeAgencyIDSpecified() As Boolean
            Get
                Return Me.schemeAgencySchemeAgencyIDFieldSpecified
            End Get
            Set
                Me.schemeAgencySchemeAgencyIDFieldSpecified = value
                Me.RaisePropertyChanged("schemeAgencySchemeAgencyIDSpecified")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="token")>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
                Me.RaisePropertyChanged("Value")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sap.com/xi/AP/Common/GDT")>  _
    Partial Public Class BusinessDocumentBasicMessageHeader
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idField As BusinessDocumentMessageID
        
        Private uUIDField As UUID
        
        Private referenceIDField As BusinessDocumentMessageID
        
        Private referenceUUIDField As UUID
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property ID() As BusinessDocumentMessageID
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("ID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property UUID() As UUID
            Get
                Return Me.uUIDField
            End Get
            Set
                Me.uUIDField = value
                Me.RaisePropertyChanged("UUID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property ReferenceID() As BusinessDocumentMessageID
            Get
                Return Me.referenceIDField
            End Get
            Set
                Me.referenceIDField = value
                Me.RaisePropertyChanged("ReferenceID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property ReferenceUUID() As UUID
            Get
                Return Me.referenceUUIDField
            End Get
            Set
                Me.referenceUUIDField = value
                Me.RaisePropertyChanged("ReferenceUUID")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://0014438665-one-off.sap.com/Y640YVQUY_")>  _
    Partial Public Class EX_BodegaExistencia_BodegaCreateRequestMessage_sync
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private basicMessageHeaderField As BusinessDocumentBasicMessageHeader
        
        Private eX_BodegaField As EX_BodegaExistencia_BodegaCreateRequest
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property BasicMessageHeader() As BusinessDocumentBasicMessageHeader
            Get
                Return Me.basicMessageHeaderField
            End Get
            Set
                Me.basicMessageHeaderField = value
                Me.RaisePropertyChanged("BasicMessageHeader")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property EX_Bodega() As EX_BodegaExistencia_BodegaCreateRequest
            Get
                Return Me.eX_BodegaField
            End Get
            Set
                Me.eX_BodegaField = value
                Me.RaisePropertyChanged("EX_Bodega")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://0014438665-one-off.sap.com/Y640YVQUY_", ConfigurationName:="WSDL_BODEGAS.Y640YVQUY_WSDL_BODEGAS")>  _
    Public Interface Y640YVQUY_WSDL_BODEGAS
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación Create no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="http://0014438665-one-off.sap.com/Y640YVQUY_/Y640YVQUY_WSDL_BODEGAS/CreateRequest"& _ 
            "", ReplyAction:="*"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSDL_BODEGAS.StandardFaultMessage), Action:="http://0014438665-one-off.sap.com/Y640YVQUY_/Y640YVQUY_WSDL_BODEGAS/CreateRequest"& _ 
            "", Name:="StandardFaultMessage", [Namespace]:="http://sap.com/xi/AP/Common/Global"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Create(ByVal request As WSDL_BODEGAS.CreateRequest) As WSDL_BODEGAS.CreateResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://0014438665-one-off.sap.com/Y640YVQUY_/Y640YVQUY_WSDL_BODEGAS/CreateRequest"& _ 
            "", ReplyAction:="*")>  _
        Function CreateAsync(ByVal request As WSDL_BODEGAS.CreateRequest) As System.Threading.Tasks.Task(Of WSDL_BODEGAS.CreateResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación Update no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="http://0014438665-one-off.sap.com/Y640YVQUY_/Y640YVQUY_WSDL_BODEGAS/UpdateRequest"& _ 
            "", ReplyAction:="*"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSDL_BODEGAS.StandardFaultMessage), Action:="http://0014438665-one-off.sap.com/Y640YVQUY_/Y640YVQUY_WSDL_BODEGAS/UpdateRequest"& _ 
            "", Name:="StandardFaultMessage", [Namespace]:="http://sap.com/xi/AP/Common/Global"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Update(ByVal request As WSDL_BODEGAS.UpdateRequest) As WSDL_BODEGAS.UpdateResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://0014438665-one-off.sap.com/Y640YVQUY_/Y640YVQUY_WSDL_BODEGAS/UpdateRequest"& _ 
            "", ReplyAction:="*")>  _
        Function UpdateAsync(ByVal request As WSDL_BODEGAS.UpdateRequest) As System.Threading.Tasks.Task(Of WSDL_BODEGAS.UpdateResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación Read no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="http://0014438665-one-off.sap.com/Y640YVQUY_/Y640YVQUY_WSDL_BODEGAS/ReadRequest", ReplyAction:="*"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSDL_BODEGAS.StandardFaultMessage), Action:="http://0014438665-one-off.sap.com/Y640YVQUY_/Y640YVQUY_WSDL_BODEGAS/ReadRequest", Name:="StandardFaultMessage", [Namespace]:="http://sap.com/xi/AP/Common/Global"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Read(ByVal request As WSDL_BODEGAS.ReadRequest) As WSDL_BODEGAS.ReadResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://0014438665-one-off.sap.com/Y640YVQUY_/Y640YVQUY_WSDL_BODEGAS/ReadRequest", ReplyAction:="*")>  _
        Function ReadAsync(ByVal request As WSDL_BODEGAS.ReadRequest) As System.Threading.Tasks.Task(Of WSDL_BODEGAS.ReadResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CreateRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sap.com/xi/SAPGlobal20/Global", Order:=0)>  _
        Public EX_BodegaExistencia_BodegaCreateRequest_sync As WSDL_BODEGAS.EX_BodegaExistencia_BodegaCreateRequestMessage_sync
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EX_BodegaExistencia_BodegaCreateRequest_sync As WSDL_BODEGAS.EX_BodegaExistencia_BodegaCreateRequestMessage_sync)
            MyBase.New
            Me.EX_BodegaExistencia_BodegaCreateRequest_sync = EX_BodegaExistencia_BodegaCreateRequest_sync
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CreateResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sap.com/xi/SAPGlobal20/Global", Order:=0)>  _
        Public EX_BodegaExistencia_BodegaCreateConfirmation_sync As WSDL_BODEGAS.EX_BodegaExistencia_BodegaCreateConfirmationMessage_sync
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EX_BodegaExistencia_BodegaCreateConfirmation_sync As WSDL_BODEGAS.EX_BodegaExistencia_BodegaCreateConfirmationMessage_sync)
            MyBase.New
            Me.EX_BodegaExistencia_BodegaCreateConfirmation_sync = EX_BodegaExistencia_BodegaCreateConfirmation_sync
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://0014438665-one-off.sap.com/Y640YVQUY_")>  _
    Partial Public Class EX_BodegaExistencia_BodegaUpdateRequestMessage_sync
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private basicMessageHeaderField As BusinessDocumentBasicMessageHeader
        
        Private eX_BodegaField As EX_BodegaExistencia_BodegaUpdateRequest
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property BasicMessageHeader() As BusinessDocumentBasicMessageHeader
            Get
                Return Me.basicMessageHeaderField
            End Get
            Set
                Me.basicMessageHeaderField = value
                Me.RaisePropertyChanged("BasicMessageHeader")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property EX_Bodega() As EX_BodegaExistencia_BodegaUpdateRequest
            Get
                Return Me.eX_BodegaField
            End Get
            Set
                Me.eX_BodegaField = value
                Me.RaisePropertyChanged("EX_Bodega")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://0014438665-one-off.sap.com/Y640YVQUY_")>  _
    Partial Public Class EX_BodegaExistencia_BodegaUpdateRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private sAP_UUIDField As String
        
        Private entryField As String
        
        Private codAlmacenField As Text
        
        Private nalmacenField As Text
        
        Private citemField As Text
        
        Private ditemField As Text
        
        Private cantDispField As Quantity
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token", Order:=0)>  _
        Public Property SAP_UUID() As String
            Get
                Return Me.sAP_UUIDField
            End Get
            Set
                Me.sAP_UUIDField = value
                Me.RaisePropertyChanged("SAP_UUID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token", Order:=1)>  _
        Public Property Entry() As String
            Get
                Return Me.entryField
            End Get
            Set
                Me.entryField = value
                Me.RaisePropertyChanged("Entry")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property CodAlmacen() As Text
            Get
                Return Me.codAlmacenField
            End Get
            Set
                Me.codAlmacenField = value
                Me.RaisePropertyChanged("CodAlmacen")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property Nalmacen() As Text
            Get
                Return Me.nalmacenField
            End Get
            Set
                Me.nalmacenField = value
                Me.RaisePropertyChanged("Nalmacen")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property Citem() As Text
            Get
                Return Me.citemField
            End Get
            Set
                Me.citemField = value
                Me.RaisePropertyChanged("Citem")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property Ditem() As Text
            Get
                Return Me.ditemField
            End Get
            Set
                Me.ditemField = value
                Me.RaisePropertyChanged("Ditem")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property CantDisp() As Quantity
            Get
                Return Me.cantDispField
            End Get
            Set
                Me.cantDispField = value
                Me.RaisePropertyChanged("CantDisp")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://0014438665-one-off.sap.com/Y640YVQUY_")>  _
    Partial Public Class EX_BodegaExistencia_BodegaUpdateConfirmationMessage_sync
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private logField As Log
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property Log() As Log
            Get
                Return Me.logField
            End Get
            Set
                Me.logField = value
                Me.RaisePropertyChanged("Log")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sap.com/xi/SAPGlobal20/Global", Order:=0)>  _
        Public EX_BodegaExistencia_BodegaUpdateRequest_sync As WSDL_BODEGAS.EX_BodegaExistencia_BodegaUpdateRequestMessage_sync
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EX_BodegaExistencia_BodegaUpdateRequest_sync As WSDL_BODEGAS.EX_BodegaExistencia_BodegaUpdateRequestMessage_sync)
            MyBase.New
            Me.EX_BodegaExistencia_BodegaUpdateRequest_sync = EX_BodegaExistencia_BodegaUpdateRequest_sync
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sap.com/xi/SAPGlobal20/Global", Order:=0)>  _
        Public EX_BodegaExistencia_BodegaUpdateConfirmation_sync As WSDL_BODEGAS.EX_BodegaExistencia_BodegaUpdateConfirmationMessage_sync
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EX_BodegaExistencia_BodegaUpdateConfirmation_sync As WSDL_BODEGAS.EX_BodegaExistencia_BodegaUpdateConfirmationMessage_sync)
            MyBase.New
            Me.EX_BodegaExistencia_BodegaUpdateConfirmation_sync = EX_BodegaExistencia_BodegaUpdateConfirmation_sync
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://0014438665-one-off.sap.com/Y640YVQUY_")>  _
    Partial Public Class EX_BodegaExistencia_BodegaReadByIDQueryMessage_sync
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private eX_BodegaField As EX_BodegaExistencia_BodegaReadByIDQuery
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property EX_Bodega() As EX_BodegaExistencia_BodegaReadByIDQuery
            Get
                Return Me.eX_BodegaField
            End Get
            Set
                Me.eX_BodegaField = value
                Me.RaisePropertyChanged("EX_Bodega")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://0014438665-one-off.sap.com/Y640YVQUY_")>  _
    Partial Public Class EX_BodegaExistencia_BodegaReadByIDQuery
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private sAP_UUIDField As String
        
        Private entryField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token", Order:=0)>  _
        Public Property SAP_UUID() As String
            Get
                Return Me.sAP_UUIDField
            End Get
            Set
                Me.sAP_UUIDField = value
                Me.RaisePropertyChanged("SAP_UUID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token", Order:=1)>  _
        Public Property Entry() As String
            Get
                Return Me.entryField
            End Get
            Set
                Me.entryField = value
                Me.RaisePropertyChanged("Entry")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://0014438665-one-off.sap.com/Y640YVQUY_")>  _
    Partial Public Class EX_BodegaExistencia_BodegaReadByIDResponseMessage_sync
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private eX_BodegaField As EX_BodegaExistencia_BodegaReadByIDResponse
        
        Private logField As Log
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property EX_Bodega() As EX_BodegaExistencia_BodegaReadByIDResponse
            Get
                Return Me.eX_BodegaField
            End Get
            Set
                Me.eX_BodegaField = value
                Me.RaisePropertyChanged("EX_Bodega")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property Log() As Log
            Get
                Return Me.logField
            End Get
            Set
                Me.logField = value
                Me.RaisePropertyChanged("Log")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://0014438665-one-off.sap.com/Y640YVQUY_")>  _
    Partial Public Class EX_BodegaExistencia_BodegaReadByIDResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private sAP_UUIDField As String
        
        Private entryField As String
        
        Private codAlmacenField As Text
        
        Private nalmacenField As Text
        
        Private citemField As Text
        
        Private ditemField As Text
        
        Private cantDispField As Quantity
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token", Order:=0)>  _
        Public Property SAP_UUID() As String
            Get
                Return Me.sAP_UUIDField
            End Get
            Set
                Me.sAP_UUIDField = value
                Me.RaisePropertyChanged("SAP_UUID")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token", Order:=1)>  _
        Public Property Entry() As String
            Get
                Return Me.entryField
            End Get
            Set
                Me.entryField = value
                Me.RaisePropertyChanged("Entry")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property CodAlmacen() As Text
            Get
                Return Me.codAlmacenField
            End Get
            Set
                Me.codAlmacenField = value
                Me.RaisePropertyChanged("CodAlmacen")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property Nalmacen() As Text
            Get
                Return Me.nalmacenField
            End Get
            Set
                Me.nalmacenField = value
                Me.RaisePropertyChanged("Nalmacen")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property Citem() As Text
            Get
                Return Me.citemField
            End Get
            Set
                Me.citemField = value
                Me.RaisePropertyChanged("Citem")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property Ditem() As Text
            Get
                Return Me.ditemField
            End Get
            Set
                Me.ditemField = value
                Me.RaisePropertyChanged("Ditem")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property CantDisp() As Quantity
            Get
                Return Me.cantDispField
            End Get
            Set
                Me.cantDispField = value
                Me.RaisePropertyChanged("CantDisp")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ReadRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sap.com/xi/SAPGlobal20/Global", Order:=0)>  _
        Public EX_BodegaExistencia_BodegaReadByIDQuery_sync As WSDL_BODEGAS.EX_BodegaExistencia_BodegaReadByIDQueryMessage_sync
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EX_BodegaExistencia_BodegaReadByIDQuery_sync As WSDL_BODEGAS.EX_BodegaExistencia_BodegaReadByIDQueryMessage_sync)
            MyBase.New
            Me.EX_BodegaExistencia_BodegaReadByIDQuery_sync = EX_BodegaExistencia_BodegaReadByIDQuery_sync
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ReadResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sap.com/xi/SAPGlobal20/Global", Order:=0)>  _
        Public EX_BodegaExistencia_BodegaReadByIDResponse_sync As WSDL_BODEGAS.EX_BodegaExistencia_BodegaReadByIDResponseMessage_sync
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EX_BodegaExistencia_BodegaReadByIDResponse_sync As WSDL_BODEGAS.EX_BodegaExistencia_BodegaReadByIDResponseMessage_sync)
            MyBase.New
            Me.EX_BodegaExistencia_BodegaReadByIDResponse_sync = EX_BodegaExistencia_BodegaReadByIDResponse_sync
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface Y640YVQUY_WSDL_BODEGASChannel
        Inherits WSDL_BODEGAS.Y640YVQUY_WSDL_BODEGAS, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Y640YVQUY_WSDL_BODEGASClient
        Inherits System.ServiceModel.ClientBase(Of WSDL_BODEGAS.Y640YVQUY_WSDL_BODEGAS)
        Implements WSDL_BODEGAS.Y640YVQUY_WSDL_BODEGAS
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSDL_BODEGAS_Y640YVQUY_WSDL_BODEGAS_Create(ByVal request As WSDL_BODEGAS.CreateRequest) As WSDL_BODEGAS.CreateResponse Implements WSDL_BODEGAS.Y640YVQUY_WSDL_BODEGAS.Create
            Return MyBase.Channel.Create(request)
        End Function
        
        Public Function Create(ByVal EX_BodegaExistencia_BodegaCreateRequest_sync As WSDL_BODEGAS.EX_BodegaExistencia_BodegaCreateRequestMessage_sync) As WSDL_BODEGAS.EX_BodegaExistencia_BodegaCreateConfirmationMessage_sync
            Dim inValue As WSDL_BODEGAS.CreateRequest = New WSDL_BODEGAS.CreateRequest()
            inValue.EX_BodegaExistencia_BodegaCreateRequest_sync = EX_BodegaExistencia_BodegaCreateRequest_sync
            Dim retVal As WSDL_BODEGAS.CreateResponse = CType(Me,WSDL_BODEGAS.Y640YVQUY_WSDL_BODEGAS).Create(inValue)
            Return retVal.EX_BodegaExistencia_BodegaCreateConfirmation_sync
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSDL_BODEGAS_Y640YVQUY_WSDL_BODEGAS_CreateAsync(ByVal request As WSDL_BODEGAS.CreateRequest) As System.Threading.Tasks.Task(Of WSDL_BODEGAS.CreateResponse) Implements WSDL_BODEGAS.Y640YVQUY_WSDL_BODEGAS.CreateAsync
            Return MyBase.Channel.CreateAsync(request)
        End Function
        
        Public Function CreateAsync(ByVal EX_BodegaExistencia_BodegaCreateRequest_sync As WSDL_BODEGAS.EX_BodegaExistencia_BodegaCreateRequestMessage_sync) As System.Threading.Tasks.Task(Of WSDL_BODEGAS.CreateResponse)
            Dim inValue As WSDL_BODEGAS.CreateRequest = New WSDL_BODEGAS.CreateRequest()
            inValue.EX_BodegaExistencia_BodegaCreateRequest_sync = EX_BodegaExistencia_BodegaCreateRequest_sync
            Return CType(Me,WSDL_BODEGAS.Y640YVQUY_WSDL_BODEGAS).CreateAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSDL_BODEGAS_Y640YVQUY_WSDL_BODEGAS_Update(ByVal request As WSDL_BODEGAS.UpdateRequest) As WSDL_BODEGAS.UpdateResponse Implements WSDL_BODEGAS.Y640YVQUY_WSDL_BODEGAS.Update
            Return MyBase.Channel.Update(request)
        End Function
        
        Public Function Update(ByVal EX_BodegaExistencia_BodegaUpdateRequest_sync As WSDL_BODEGAS.EX_BodegaExistencia_BodegaUpdateRequestMessage_sync) As WSDL_BODEGAS.EX_BodegaExistencia_BodegaUpdateConfirmationMessage_sync
            Dim inValue As WSDL_BODEGAS.UpdateRequest = New WSDL_BODEGAS.UpdateRequest()
            inValue.EX_BodegaExistencia_BodegaUpdateRequest_sync = EX_BodegaExistencia_BodegaUpdateRequest_sync
            Dim retVal As WSDL_BODEGAS.UpdateResponse = CType(Me,WSDL_BODEGAS.Y640YVQUY_WSDL_BODEGAS).Update(inValue)
            Return retVal.EX_BodegaExistencia_BodegaUpdateConfirmation_sync
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSDL_BODEGAS_Y640YVQUY_WSDL_BODEGAS_UpdateAsync(ByVal request As WSDL_BODEGAS.UpdateRequest) As System.Threading.Tasks.Task(Of WSDL_BODEGAS.UpdateResponse) Implements WSDL_BODEGAS.Y640YVQUY_WSDL_BODEGAS.UpdateAsync
            Return MyBase.Channel.UpdateAsync(request)
        End Function
        
        Public Function UpdateAsync(ByVal EX_BodegaExistencia_BodegaUpdateRequest_sync As WSDL_BODEGAS.EX_BodegaExistencia_BodegaUpdateRequestMessage_sync) As System.Threading.Tasks.Task(Of WSDL_BODEGAS.UpdateResponse)
            Dim inValue As WSDL_BODEGAS.UpdateRequest = New WSDL_BODEGAS.UpdateRequest()
            inValue.EX_BodegaExistencia_BodegaUpdateRequest_sync = EX_BodegaExistencia_BodegaUpdateRequest_sync
            Return CType(Me,WSDL_BODEGAS.Y640YVQUY_WSDL_BODEGAS).UpdateAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSDL_BODEGAS_Y640YVQUY_WSDL_BODEGAS_Read(ByVal request As WSDL_BODEGAS.ReadRequest) As WSDL_BODEGAS.ReadResponse Implements WSDL_BODEGAS.Y640YVQUY_WSDL_BODEGAS.Read
            Return MyBase.Channel.Read(request)
        End Function
        
        Public Function Read(ByVal EX_BodegaExistencia_BodegaReadByIDQuery_sync As WSDL_BODEGAS.EX_BodegaExistencia_BodegaReadByIDQueryMessage_sync) As WSDL_BODEGAS.EX_BodegaExistencia_BodegaReadByIDResponseMessage_sync
            Dim inValue As WSDL_BODEGAS.ReadRequest = New WSDL_BODEGAS.ReadRequest()
            inValue.EX_BodegaExistencia_BodegaReadByIDQuery_sync = EX_BodegaExistencia_BodegaReadByIDQuery_sync
            Dim retVal As WSDL_BODEGAS.ReadResponse = CType(Me,WSDL_BODEGAS.Y640YVQUY_WSDL_BODEGAS).Read(inValue)
            Return retVal.EX_BodegaExistencia_BodegaReadByIDResponse_sync
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSDL_BODEGAS_Y640YVQUY_WSDL_BODEGAS_ReadAsync(ByVal request As WSDL_BODEGAS.ReadRequest) As System.Threading.Tasks.Task(Of WSDL_BODEGAS.ReadResponse) Implements WSDL_BODEGAS.Y640YVQUY_WSDL_BODEGAS.ReadAsync
            Return MyBase.Channel.ReadAsync(request)
        End Function
        
        Public Function ReadAsync(ByVal EX_BodegaExistencia_BodegaReadByIDQuery_sync As WSDL_BODEGAS.EX_BodegaExistencia_BodegaReadByIDQueryMessage_sync) As System.Threading.Tasks.Task(Of WSDL_BODEGAS.ReadResponse)
            Dim inValue As WSDL_BODEGAS.ReadRequest = New WSDL_BODEGAS.ReadRequest()
            inValue.EX_BodegaExistencia_BodegaReadByIDQuery_sync = EX_BodegaExistencia_BodegaReadByIDQuery_sync
            Return CType(Me,WSDL_BODEGAS.Y640YVQUY_WSDL_BODEGAS).ReadAsync(inValue)
        End Function
    End Class
End Namespace
